import Layout from "components/Layout";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button>Add</button>
        <input type="search" />
        <button>search</button>
      </div>
    </Layout>
  );
};

export default Home;
