/* eslint-disable @next/next/no-img-element */
import Layout from "components/Layout";
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { chooseRamdomImage } from "utils/chooseRamdomImage";
import styled from "styled-components";
import { darken, lighten } from "polished";

const Home: NextPage = () => {
  const imageSelected = chooseRamdomImage();
  console.log(imageSelected);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ContainerLeft>
          <img src="/images/main01.jpg" alt="imagem de louvor" />
        </ContainerLeft>
        <ContainerRight>
          <Form>
            <Title>Busque o seu momento com Deus</Title>
            <RowForm>
              <label htmlFor="city">Cidade:</label>
              <select id="city">
                <option value="0">Selecione</option>
                <option value="1">Goianésia</option>
                <option value="2">Santa Rita do Novo Destino</option>
              </select>
            </RowForm>
            <RowForm>
              <label htmlFor="segment">Segmento:</label>
              <select id="segment">
                <option value="0">Selecione</option>
                <option value="1">Católico</option>
                <option value="2">Evangélico</option>
              </select>
            </RowForm>
            <RowForm>
              <button type="button">Buscar</button>
            </RowForm>
          </Form>
        </ContainerRight>
      </Container>
    </Layout>
  );
};

const Container = styled.div`
  display: flex;
  flex-direction: column;
  gap: 10px;
  min-height: calc(84vh - 15px);
`;

const ContainerLeft = styled.aside`
  width: 90%;
  margin: 0 auto;
  background-color: yellow;
  height: calc(84vh * 0.47);
  border-radius: 10px;

  img {
    width: 100%;
    height: 100%;
    border-radius: 10px;
  }
`;

const ContainerRight = styled.aside`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: calc(84vh * 0.47);
`;

const Title = styled.h3`
  font-family: "PoppinsBold", sans-serif;
  text-transform: uppercase;
  margin-bottom: 25px;
`;

const Form = styled.form`
  display: flex;
  flex-direction: column;
  width: 90%;
  border: 1px solid ${(props) => props.theme.colors.text};
  border-radius: 10px;
  padding: 25px 15px;
`;

const RowForm = styled.div`
  display: flex;
  align-items: center;
  flex: 1;
  padding: 2px;
  margin-bottom: 5px;

  label {
    padding-right: 5px;
    font-family: "Roboto", sans-serif;
    width: 25%;
    text-align: right;
  }

  input,
  select {
    width: 75%;
    text-align: left;
  }

  button {
    width: 100%;
    margin: 0 auto;
    margin-top: 20px;
    padding: 10px 0;
    background-color: ${(props) => props.theme.colors.secondary};
    color: ${(props) => props.theme.colors.text};
    font-weight: bold;
    border-radius: 10px;
    transition: all 0.2s;

    &:hover {
      background-color: ${(props) =>
        props.title === "dark"
          ? lighten(0.1, props.theme.colors.secondary)
          : darken(0.1, props.theme.colors.secondary)};
      color: white;
    }
  }
`;

export default Home;
